create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  full_name text,
  created_at timestamptz default now()
);

create table if not exists public.scans (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  url text not null,
  prediction text not null,
  confidence double precision not null,
  risk_score text not null,
  safety_score integer not null,
  scan_time double precision not null,
  created_at timestamptz default now()
);

create table if not exists public.threats (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  domain text not null,
  threat_level text not null,
  detected_at timestamptz default now()
);

alter table public.scans enable row level security;
alter table public.threats enable row level security;
alter table public.profiles enable row level security;

create policy "users_can_view_their_scans" on public.scans
for select using (auth.uid() = user_id);

create policy "users_can_insert_their_scans" on public.scans
for insert with check (auth.uid() = user_id);

create policy "users_can_view_their_threats" on public.threats
for select using (auth.uid() = user_id);

create policy "users_can_insert_their_threats" on public.threats
for insert with check (auth.uid() = user_id);

create policy "users_can_view_their_profile" on public.profiles
for select using (auth.uid() = id);

create policy "users_can_update_their_profile" on public.profiles
for update using (auth.uid() = id);
